### PR TITLE
feat: show weather info current location instead of "New York City"

### LINKED ISSUE #3: Using Geolocation API to get the users location
Using the Geolocation API to get the users location as the first weather results displayed, instead of just New York City.

Read more [here](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API).

### PR DESCRIPTION
**Pull request by KhudaDad414**
### Context
Currently, the website shows New York's weather, this PR will enable to the website to show the user's location weather.

## Contributers
@KhudaDad414 @yyjlincoln 
### Related Issues
Closes #3

### CODE REVIEW

**Review by yyjlincoln — APPROVED** [review]
LGTM

**Review by ditsuke — APPROVED** [review]
LGTM

**Comment by ditsuke** [comment]
Good to merge

**Comment by ditsuke** [comment]
@KhudaDad414 @yyjlincoln @VaibhaveS this has some conflicts preventing merge, PTAL so we can merge!

**Comment by yyjlincoln** [comment]
@ditsuke I've fixed the merge conflict & also added a small feature to allow the user to search their city without having to choose from the list. Some very small suburbs might not be on the list. PTAL

**Comment by yyjlincoln** [comment]
cc @KhudaDad414 @yyjlincoln @VaibhaveS

**Comment by ditsuke** [comment]
> @ditsuke I've fixed the merge conflict & also added a small feature to allow the user to search their city without having to choose from the list. Some very small suburbs might not be on the list. PTAL

@yyjlincoln 
I really like the new feature, nicely done! Since we already had the approvals and only have a minor change since, I'll go ahead and merge this in.

**Pull request merged**
