### PR TITLE
Fix location button and layout issues; cleanup and remove console logs

### PR DESCRIPTION
**Pull request by ditsuke**
## Summary
- Location button is fixed! 🥳
- Layout responsiveness is improved! Things looks much nicer both on mobile and desktop.
- Commented out code is removed!
- Console logs we used for debugging are gone 😉 
- Minor optimization with `useMemo()` to initialize the API wrapper.

.. open for more commits 😛

### CODE REVIEW

**Review by anubhav06 — APPROVED** [review]
LGTM ! 😆🎉

**Comment by harshsharma6401** [comment]
Amazing 😁

**Review by harshsharma6401 — APPROVED** [review]

**Comment by CIPHERTron** [comment]
You forgot to add one more fix i.e. adding some top & bottom margin to the alert container. Sending one commit your way 🤣

**Review by CIPHERTron — APPROVED** [review]
Rest all LGTM 🎉

**Comment by CIPHERTron** [comment]
Merging it in since we've 3 approvals and all the tests are passing xD

**Pull request merged**
