### PR TITLE
Weather warnings

### LINKED ISSUE #13: Implement weather warnings
A red banner that notifies the user of extreme weather conditions. 

E.g. 
- Typhoons
- Extreme rain
- Snow
- Heat
- Tornado

### PR DESCRIPTION
**Pull request by harshsharma6401**
### Summary
- Fixes #13. 
- Used Material UI for creating alerts.

### CODE REVIEW

**Review by KshitijDarekar — APPROVED** [review]
LGTM

**Review by anubhav06 — APPROVED** [review]
LGTM! 🎉

**Comment by harshsharma6401** [comment]
Got sufficient approvals, so merged it!

**Comment by Chukwuemeka-Mba** [comment]
Awesome work guys!

**Review by Dhruv-Sachdev1313 — COMMENTED** [review]
Looks good to me!!

**Pull request merged**
