### PR TITLE
Fix ESLint and Prettier rule violations

### LINKED ISSUE #30: Fix code quality violations reported by ESLint
Now that we've merged in #17, builds are failing since we have multiple violations of ESLint rules.

### PR DESCRIPTION
**Pull request by ditsuke**
## Context
With the merge of #17 / #31 we now have a well defined set of linting and formatting rules to follow. At the moment we have several violations of these rules (some of which are level `error`), which means the current deployment is also broken. This PR fixes all these violations.

Here are the commands and actions I executed for 83217f64218c2ac465c7a93d7a7188812225c1ee:
- `yarn lint --fix`
- `yarn format`
- Refactor App.js:48 `error` => `err`; App.js:70 `city` => `selectedCity` to
  fix ESLint's `no-shadow` rule violations.

## More Information
This PR closes #30 

- [x]  My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

### CODE REVIEW

**Comment by ditsuke** [comment]
@MLH-Fellowship/mlh-prep-january-2022 once you've updated the branches you're working on with `main`, please run the `yarn lint --fix` and `yarn format` commands I've mentioned above to avoid merge conflicts in your PRs.

**Review by CIPHERTron — APPROVED** [review]
LGTM 🎉 
Thanks @ditsuke

**Review by harshsharma6401 — APPROVED** [review]

**Review by KshitijDarekar — APPROVED** [review]
LGTM

**Comment by ditsuke** [comment]
Has enough reviews and a successful deploy. Merging!

**Pull request merged**
