### PR TITLE
feat: add forecast carousel

### PR DESCRIPTION
**Pull request by CIPHERTron**
Related issues: #1 #16 
-----

https://user-images.githubusercontent.com/56754747/151243628-8c95d98f-d9f2-4f09-bf5c-12bd26eb1896.mov

### CODE REVIEW

**Comment by CIPHERTron** [comment]
@VaibhaveS @Dhruv-Sachdev1313 @harshsharma6401 here's the carousel for the forecasts. You can now try to integrate the logic part to the skeleton 🚀

**Comment by harshsharma6401** [comment]
> @VaibhaveS @Dhruv-Sachdev1313 @harshsharma6401 here's the carousel for the forecasts. You can now try to integrate the logic part to the skeleton 🚀

Good Job!  A slider is also required for switching the Hourly and Weekly Forecasts.😅😁

**Comment by harshsharma6401** [comment]
> > @VaibhaveS @Dhruv-Sachdev1313 @harshsharma6401 here's the carousel for the forecasts. You can now try to integrate the logic part to the skeleton 🚀
> 
> Good Job! A slider is also required for switching the Hourly and Weekly Forecasts.😅😁

Hey! Discord server is down. I wanted some help. Please join this! https://meet.google.com/ond-mtyz-fmx

**Comment by CIPHERTron** [comment]
> > @VaibhaveS @Dhruv-Sachdev1313 @harshsharma6401 here's the carousel for the forecasts. You can now try to integrate the logic part to the skeleton 🚀
> 
> Good Job! A slider is also required for switching the Hourly and Weekly Forecasts.😅😁

Done!

**Review by harshsharma6401 — APPROVED** [review]

**Review by ditsuke — APPROVED** [review]
LGTM. @KhudaDad414 PTAL

**Comment by harshsharma6401** [comment]
> > > @VaibhaveS @Dhruv-Sachdev1313 @harshsharma6401 here's the carousel for the forecasts. You can now try to integrate the logic part to the skeleton 🚀
> > 
> > 
> > Good Job! A slider is also required for switching the Hourly and Weekly Forecasts.😅😁
> 
> Done!

Thanks ✨

**Review by KshitijDarekar — APPROVED** [review]
LGTM !

**Review by Dhruv-Sachdev1313 — APPROVED** [review]
Looks really good, Let's get this merged !!

**Pull request merged**
