### PR TITLE
Hourly and Weekly  forecasts

### LINKED ISSUE #1: Hourly Forecasts
Allow the user to put a time + date in to get an idea of what the weather will be like then. At the moment, it only displays the weather right now.

### PR DESCRIPTION
**Pull request by harshsharma6401**
### Fixes
- Fixes #1 

### Images
hourly-forecasts-1

hourly-forecasts-3

hourly-forecasts-2

### CODE REVIEW

**Review by Dhruv-Sachdev1313 — APPROVED** [review]
LGTM!!

**Comment by gmelodie** [comment]
Any ideas why the preview on my browser/PC doesn't show the same as your images? Here's how it currently looks
image

**Comment by Dhruv-Sachdev1313** [comment]
> Any ideas why the preview on my browser/PC doesn't show the same as your images? Here's how it currently looks
> image

Hey @gmelodie, We have made changes on /playground. You might have to add a /playground after your URL!!

**Review by KshitijDarekar — COMMENTED** [review]
LGTM, Although we need to pass the data from the weather API I guess. Is that going to be done after merging this PR?

**Comment by harshsharma6401** [comment]
> LGTM, Although we need to pass the data from the weather API I guess. Is that going to be done after merging this PR?

Yes!

**Comment by KshitijDarekar** [comment]
> > LGTM, Although we need to pass the data from the weather API I guess. Is that going to be done after merging this PR?
> 
> Yes!

Okay

**Review by KshitijDarekar — APPROVED** [review]
LGTM

**Pull request merged**
