### PR TITLE
feat: Add PWA integration

### PR DESCRIPTION
**Pull request by CIPHERTron**
fixes #26

### CODE REVIEW

**Comment by CIPHERTron** [comment]
@ditsuke @KshitijDarekar @harshsharma6401 we can discuss the PWA issue here and proceed further 🚀 

As of now, I've set up the service worker config and registered the same. After this, we'll be requiring the manifest as well as favicons. Then we can test the PWA

**Comment by ditsuke** [comment]
So we already have a manifest. The icons are react default, but I think that belongs to another issue and PR?

image

**Comment by KshitijDarekar** [comment]
> 
Manifest doesn't have a maskable icon, we need to add it. The icons are React's default(react provides it at the time of installation), we may keep it the same or if someone is good at designing a logo we can change it.

**Comment by CIPHERTron** [comment]
> > 
> 
> Manifest doesn't have a maskable icon, we need to add it. The icons are React's default(react provides it at the time of installation), we may keep it the same or if someone is good at designing a logo we can change it.

Ughhh.....I'm thinking of transitioning to the field of designing. There's clearly a huge demand of designers haha

Btw can we use [this](https://avatars.githubusercontent.com/u/65834464?s=200&v=4) icon by changing it from `.png` to `.ico` format and then resize the image using https://imageresizer.com/ ?
and should we do it in this PR or in another PR?

Open to suggestions though

**Comment by ditsuke** [comment]
Let's call the design folks

/cc Super Duper Figma Team @yyjlincoln @psahithireddy @Riyadevvarshney11 @Chukwuemeka-Mba

**Comment by CIPHERTron** [comment]
@ditsuke @KshitijDarekar do you think maybe we should skip the icons part and change this PR's status to ready-for-review?

**Comment by KshitijDarekar** [comment]
> @ditsuke @KshitijDarekar do you think maybe we should skip the icons part and change this PR's status to ready-for-review?

@CIPHERTron I have added the purpose field for the icons array. This way it won't show that manifest doesn't have a maskable icon and we can change the icons any time.

**Comment by KshitijDarekar** [comment]
Also there is this tool to create a proper maskable icon.
https://maskable.app/editor

**Comment by ditsuke** [comment]
I think we should open it up now. Since it looks like we agree I'll go ahead and do it

**Comment by CIPHERTron** [comment]
> > @ditsuke @KshitijDarekar do you think maybe we should skip the icons part and change this PR's status to ready-for-review?
> 
> @CIPHERTron I have added the purpose field for the icons array. This way it won't show that manifest doesn't have a maskable icon and we can change the icons any time.

Great, thanks!

**Comment by Aniket762** [comment]
LGTM! @ditsuke

**Review by yyjlincoln — APPROVED** [review]
LGTM

**Comment by ditsuke** [comment]
Merging this in.

**Pull request merged**
