### PR TITLE
Implement a Central OpenWeatherMap API Wrapper with Caching 

### LINKED ISSUE #35: Implement a Central API and Caching for OpenWeatherMap
At the moment, various components need to digest information that comes from the OpenWeatherMap API. However since we're calling the API by city name in App.js, don't pass the results as stateful props to components and use endpoints that deliver only part of the information required by our app as a whole, components have to make there own API calls or stick to App.js (#23).

The current solution is not extensible, wasteful of API calls and also looks messy in code and is not performant. Following from the discussion https://github.com/MLH-Fellowship/prep-project-jan-2022/pull/23#issuecomment-1019099580, and @yyjlincoln's comments we should:
- Implement a central API driver which caches results to improve performance.
- Use OpenWeatherMap's new [One Call API](https://openweathermap.org/api/one-call-api#listsource). This endpoint delivers all the information required by our components. We can deliver parts of the information through methods in our API Driver (`getWeatherInfo()`, `getWeatherWarnings()` etc).

### PR DESCRIPTION
**Pull request by ditsuke**
Creates a new OpenWeatherMap module, implement members for caching and roughly lays out public facing methods.

Closes #35.

Purely WIP right now.

## Authors
@ditsuke @Chukwuemeka-Mba

### CODE REVIEW

**Comment by gmelodie** [comment]
**Note:** once this is done, update all API calls.

**Comment by ditsuke** [comment]
With the developments from yesterday, I have opened this PR up for review at this stage. We will be integrating this wrapper in the new /playground (#50 and beyond).

**Review by CIPHERTron — APPROVED** [review]
LGTM 🚀

**Review by Chukwuemeka-Mba — APPROVED** [review]
LFG! 🛸🎉

**Pull request merged**
