### PR TITLE
Target symbol for fetching location

### LINKED ISSUE #47: Make the Target symbol for fetching location
###    Improve UX with location
- By default, the website shows the weather of our location, which is fine.
- After surfing the website, when we want to check the weather of our location once again, We have to either search it, pinpoint it or reload the website. It is not the appropriate and convenient way.
- In these situations, the symbol shown below comes handy. It is present in almost every website dealing with the location; we should include it. 

Location Symbol

### PR DESCRIPTION
**Pull request by harshsharma6401**
### Fixes
- Fixes #47.

### Demo

Location-icon-PR-image2

### Contributers

-   @harshsharma6401 , @ditsuke , @CIPHERTron  , @Chukwuemeka-Mba

### CODE REVIEW

**Comment by Chukwuemeka-Mba** [comment]
Nice work! 🥇

**Review by Chukwuemeka-Mba — APPROVED** [review]

**Review by anubhav06 — APPROVED** [review]
LGTM! Just that it works locally but not when deployed. But I guess, that's already an issue that page doesn't load when location is enabled

**Review by CIPHERTron — COMMENTED** [review]
Just a suggestion(so that the design looks uniform)

We can actually give a white background to the location icon and change the color of the icon to some dark variant. Also, give a border-radius of 5px. Ig that should make it look good

If you want I can do these changes

**Comment by harshsharma6401** [comment]
> Just a suggestion(so that the design looks uniform)
> 
> We can actually give a white background to the location icon and change the color of the icon to some dark variant. Also, give a border-radius of 5px. Ig that should make it look good
> 
> If you want I can do these changes
Thanks for the suggestion. I am working on it

**Review by ditsuke — APPROVED** [review]
LGTM, nice work!

**Comment by harshsharma6401** [comment]
Since it is approved. I think it is good to go, merging it!

**Pull request merged**
