### PR TITLE
Hourly Forecasts

### LINKED ISSUE #1: Hourly Forecasts
Allow the user to put a time + date in to get an idea of what the weather will be like then. At the moment, it only displays the weather right now.

### PR DESCRIPTION
**Pull request by harshsharma6401**
Fixes #1

### CODE REVIEW

**Comment by gmelodie** [comment]
Any news on this?

**Review by KhudaDad414 — COMMENTED** [review]
Hey, just wanted to let you know that all the new changes need to be made in `/playground` which has the components for this feature.

**Comment by Dhruv-Sachdev1313** [comment]
> Hey, just wanted to let you know that all the new changes need to be made in `/playground` which has the components for this feature.

Hi @KhudaDad414, Yes we did look at the new components in the /playground and even started working with them(in the `hourly-forecast` branch on this repo). To be very honest I have no idea how are we going to merge these two things. I find it easier to just add the changes from here to the new components. But let's see...

**Comment by gmelodie** [comment]
Closing this as it should be included in #56

**Pull request closed without merging**
