### PR TITLE
Eslint + Prettier +Airbnb Style issue#10

### PR DESCRIPTION
**Pull request by KshitijDarekar**
**Summary**
Tools like ESLint and Prettier makes it easier for developers to enforce their team's chosen coding standards.

**Describe the solution you'd like**
 - [x] Setup Eslint
 - [x] Setup Prettier
 - [x] Airbnb Style

**Extras**
We could try adding husky and lint-staged, we are already discussing it [here](https://github.com/MLH-Fellowship/prep-project-jan-2022/issues/10).

## Author
@ditsuke @KshitijDarekar  

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

## Additional Info
This PR closes [issue#10](https://github.com/MLH-Fellowship/prep-project-jan-2022/issues/10)

### CODE REVIEW

**Review by harshsharma6401 — APPROVED** [review]

**Comment by gmelodie** [comment]
Make sure to pull recent changes from `origin:main`. Consider using [pull](https://github.com/apps/pull) on your forks to make they're up to date

**Comment by ditsuke** [comment]
> Make sure to pull recent changes from `origin:main`. Consider using [pull](https://github.com/apps/pull) on your forks to make they're up to date

Fixes out in a [PR](https://github.com/KshitijDarekar/prep-project-jan-2022/pull/5) to the parent branch!

**Review by yyjlincoln — APPROVED** [review]
LGTM

**Review by KhudaDad414 — APPROVED** [review]
LGTM

**Comment by ditsuke** [comment]
Merge ready!

**Comment by yyjlincoln** [comment]
Merge ready

**Comment by ditsuke** [comment]
Rebased to 67d8e8b

**Comment by ditsuke** [comment]
Sorry, I forgot to squash the commits and had to revert this merge! We'll need a PR for this again!

**Pull request merged**
